#spring.application.name=oauth2-last
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks
      client:
        provider:
          spring:
            authorization-uri: http://127.0.0.1:8080/oauth2/authorize
            token-uri: http://127.0.0.1:8080/oauth2/token
            user-info-uri: http://127.0.0.1:8080/user
            jwk-set-uri: http://127.0.0.1:8080/oauth2/jwks
            user-name-attribute: sub
